# 连接数据库信息
SQL:
  server: "rm-8vb1qy124u08ic535.mysql.zhangbei.rds.aliyuncs.com"
  user: "bcadmin"
  password: "s%j1RDR^%D9ntIKCi#Uv"
  database: "gongchuang"

# 本地Flask信息
LOCAL_INFO:
  local_host: "172.31.85.168"
  flask_port: 5000

MODEL:
  # 文本转向量模型
  doc2vec_model: "./models/exp0/d2v_model"

  # tfidf模型 暂时不用
  tfidf_enc_user: ""
  svd_tag_user: ""
  tfidf_enc_jd: ""
  svd_tag_jd: ""

  # 用户是否投递、HR是否满意 分类模型
  delivered_model: "./models/exp6/lgb_delivered_model.txt"
  satisfied_model: "./models/exp6/lgb_satisfied_model.txt"

  #  以下两个参数使用arg控制
#  use_doc2vec : True
#  use_tfidf: False

